name-template: 'Nächstes Release'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bugfix', 'bug']

# Vereinfachtes Template ohne $LABELS
change-template: |
  ### $TITLE - #$NUMBER
  $BODY

template: |
  $CHANGES

exclude-labels:
  - 'skip-changelog'

version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'feature', 'enhancement']
  patch:
    labels: ['patch', 'bug', 'fix', 'bugfix']
  default: patch

# Replacer um "Changelog Text" aus PR-Body zu extrahieren
replacers:
  # Extrahiere nur den Changelog-Text Abschnitt
  - search: '/^###\s*Changelog\s*Text\s*:?\s*\r?\n([\s\S]*?)$/gmi'
    replace: '$1'

sort-by: 'title'
sort-direction: 'ascending'