name-template: 'Nächstes Release'
tag-template: 'v$RESOLVED_VERSION'

# Kategorisierung nach Feature/Bug
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bugfix', 'bug']

# Template pro PR
# Titel = Issue-Titel (automatisch gesetzt durch Webhook)
# Labels versteckt für Reorganisierungs-Script
change-template: |
  ### $TITLE - #$NUMBER
  <!-- labels: $LABELS -->
  <!-- BODY:START -->
  $BODY
  <!-- BODY:END -->

# Haupt-Template: Nur die Kategorien rendern
template: |
  $CHANGES

# Exclude Skip-Changelog PRs
exclude-labels:
  - 'skip-changelog'

# Version resolution
version-resolver:
  major:
    labels: ['major']
  minor:
    labels: ['minor', 'feature', 'enhancement']
  patch:
    labels: ['patch', 'bug', 'fix', 'bugfix']
  default: patch

# Replacer: Extrahiere Changelog-Text aus PR-Body
replacers:
  # 1) Finde "### Changelog Text" Sektion und übernehme alles danach bis BODY:END
  - search: '/<!-- BODY:START -->((?:(?!<!-- BODY:END -->)[\s\S])*?)^###\s*Changelog\s*Text\s*:?\s*\r?\n([\s\S]*?)<!-- BODY:END -->/gmi'
    replace: '$2'
  
  # 2) Fallback: Entferne alle verbleibenden Body-Blöcke ohne Changelog-Marker
  - search: '/<!-- BODY:START -->[\s\S]*?<!-- BODY:END -->/g'
    replace: ''

# Sortierung nach Titel (damit Issues gruppiert sind)
sort-by: 'title'
sort-direction: 'ascending'
