name-template: 'Nächstes Release'

categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bugfix', 'bug']

# Pro PR-Eintrag: Überschrift + PR-Body-Ausschnitt
change-template: |
  ### $TITLE - #$NUMBER

  <!-- BODY:START -->
  $BODY
  <!-- BODY:END -->

# $CHANGES rendert die Kategorien automatisch (nur nicht-leere)
template: |
  $CHANGES
  
exclude-labels:
  - 'skip-changelog'
  
replacers:
  # 1) Innerhalb EINES Body-Blocks: Linie "### Changelog Text" finden,
  #    und ALLES danach bis zum BODY:END übernehmen.
  #    Das "tempered dot" ((?:(?!<!-- BODY:END -->)[\s\S])*) verhindert,
  #    dass über den eigenen BODY-Block hinaus gematcht wird.
  - search: '/<!-- BODY:START -->((?:(?!<!-- BODY:END -->)[\s\S])*?)^###\s*Changelog\s*Text\s*:?\s*\r?\n([\s\S]*?)<!-- BODY:END -->/gmi'
    replace: '$2'

  # 2) Fallback/Aufräumen: Alle übrigen Body-Blöcke (ohne Marker) komplett entfernen.
  - search: '/<!-- BODY:START -->[\s\S]*?<!-- BODY:END -->/g'
    replace: ''