name: Reorganize Release Notes

on:
  workflow_call:
    inputs:
      release-id:
        description: 'The ID of the draft release to reorganize'
        required: true
        type: string
    secrets:
      github-token:
        description: 'GitHub token with contents:write permission'
        required: true

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: MODUS-TestALGO/.github
          ref: main
          path: .github-scripts
      
      - name: Get release body
        id: get-release
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          RELEASE_BODY=$(gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases/${{ inputs.release-id }} \
            --jq '.body')
          
          # Save to file to handle multiline content
          echo "$RELEASE_BODY" > release-body.md
          echo "✓ Fetched release body (${{ inputs.release-id }})"
      
      - name: Reorganize release notes
        id: reorganize
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.event.repository.name }}"
          
          echo "Running reorganization script..."
          pwsh .github-scripts/scripts/Reorganize-ReleaseNotes.ps1 \
            -MarkdownInput "$(cat release-body.md)" \
            -Owner "$OWNER" \
            -Repo "$REPO" \
            > reorganized-body.md
          
          echo "✓ Reorganization complete"
      
      - name: Update release
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          REORGANIZED_BODY=$(cat reorganized-body.md)
          
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/releases/${{ inputs.release-id }} \
            -f "body=$REORGANIZED_BODY"
          
          echo "✅ Release updated successfully!"
      
      - name: Comment on PRs (optional)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        run: |
          echo "Release draft updated with reorganized notes"
          # Optional: Add logic to comment on PRs about release inclusion