name: Reorganize Release Notes

on:
  workflow_call:
    inputs:
      release-id:
        description: 'The ID of the draft release to reorganize'
        required: true
        type: string
      release-tag:
        description: 'The tag name of the release (will be preserved)'
        required: true
        type: string
    secrets:
      github-token:
        description: 'GitHub token with contents:write permission'
        required: true

jobs:
  reorganize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: MODUS-TestALGO/.github
          ref: main
          path: .github-scripts
      
      - name: Get release body
        id: get-release
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        shell: pwsh
        run: |
          # Set UTF-8 encoding
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          
          $releaseJson = gh api `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/${{ github.repository }}/releases/${{ inputs.release-id }}
          
          $release = $releaseJson | ConvertFrom-Json
          $release.body | Out-File -FilePath release-body.md -Encoding UTF8 -NoNewline
          
          Write-Host "✓ Fetched release body (${{ inputs.release-id }})"
      
      - name: Reorganize release notes
        id: reorganize
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        shell: pwsh
        run: |
          # Set UTF-8 encoding for correct emoji/umlaut handling
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          $PSDefaultParameterValues['*:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          
          $Owner = "${{ github.repository_owner }}"
          $Repo = "${{ github.event.repository.name }}"
          
          Write-Host "Running reorganization script..."
          
          $markdown = Get-Content release-body.md -Raw -Encoding UTF8
          $result = & .github-scripts/scripts/Reorganize-ReleaseNotes.ps1 `
            -MarkdownInput $markdown `
            -Owner $Owner `
            -Repo $Repo
          
          $result | Out-File -FilePath reorganized-body.md -Encoding UTF8 -NoNewline
          
          Write-Host "✓ Reorganization complete"
      
      - name: Update release
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        shell: pwsh
        run: |
          # Set UTF-8 encoding
          $PSDefaultParameterValues['*:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
          
          $reorganizedBody = Get-Content reorganized-body.md -Raw -Encoding UTF8
          
          $updateData = @{
            body = $reorganizedBody
          } | ConvertTo-Json -Depth 10
          
          $tempJson = New-TemporaryFile
          $updateData | Out-File -FilePath $tempJson.FullName -Encoding UTF8 -NoNewline
          
          gh api `
            --method PATCH `
            -H "Accept: application/vnd.github+json" `
            -H "X-GitHub-Api-Version: 2022-11-28" `
            /repos/${{ github.repository }}/releases/${{ inputs.release-id }} `
            --input $tempJson.FullName
          
          Remove-Item $tempJson.FullName -Force -ErrorAction SilentlyContinue
          
          Write-Host "✅ Release updated successfully!"
      
      - name: Comment on PRs (optional)
        if: success()
        env:
          GH_TOKEN: ${{ secrets.github-token }}
        shell: pwsh
        run: |
          Write-Host "Release draft updated with reorganized notes"
          # Optional: Add logic to comment on PRs about release inclusion
